public:
  encoding: utf8
  adapter: postgresql
  host: 159.203.80.25
  port: 5432
  database: aact
  username: ctti
  password: PASS
staging:
  encoding: utf8
  adapter: postgresql
  host: 159.203.80.25
  port: 5432
  database: aact_alt
  username: ctti
  password: PASS